name: Docker Image Transfer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  transfer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine

      - name: Tag Docker image
        run: |
          docker tag registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine ${{ secrets.DOCKERHUB_USERNAME }}/wechotd:alpine

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wechotd:alpine
